name: safebank-infra

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
      branches:
        - '*'
      paths-ignore:
        - 'scripts/**'

env:
  RESOURCE_GROUP_UAT: BCSAI2024-DEVOPS-STUDENTS-A-UAT
  RESOURCE_GROUP_DEV: BCSAI2024-DEVOPS-STUDENTS-A-DEV
  RESOURCE_GROUP_PROD: BCSAI2024-DEVOPS-STUDENTS-A-PROD
  SUBSCRIPTION_ID_DEV: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_UAT: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  SUBSCRIPTION_ID_PROD: e0b9cada-61bc-4b5a-bd7a-52c606726b3b
  USER_ALIAS: rorosaga

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

    - name: Upload Bicep build artifact
      uses: actions/upload-artifact@v3
      with:
        name: bicep-build
        path: ./main.bicep 

  deploy-dev:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'DEV'

    steps:

      # Checkout code
    - uses: actions/checkout@main
  
    - name: Download Bicep build artifact
      uses: actions/download-artifact@v3
      with:
          name: bicep-build
    
      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy DEV
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_DEV }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_DEV }}
        template: ./main.bicep
        parameters: ./parameters/dev.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
        deploymentName: ${{ env.USER_ALIAS }}-dev
      
  deploy-uat:
    if: (github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main') || (github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'UAT'

    steps:

      - uses: actions/checkout@main

      - name: Download Bicep build artifact
        uses: actions/download-artifact@v3
        with:
          name: bicep-build

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy UAT
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION_ID_UAT }}
          resourceGroupName: ${{ env.RESOURCE_GROUP_UAT }}
          template: ./main.bicep
          parameters: ./parameters/uat.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
          deploymentName: ${{ env.USER_ALIAS }}-uat


  deploy-prod:
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'PROD'

    steps:

      # Checkout code
    - uses: actions/checkout@main
  
    - name: Download Bicep build artifact
      uses: actions/download-artifact@v3
      with:
          name: bicep-build
    
      # Log into Azure
    - uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy DEV
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID_PROD }}
        resourceGroupName: ${{ env.RESOURCE_GROUP_PROD }}
        template: ./main.bicep
        parameters: ./parameters/prod.bicepparam appServiceAPIEnvVarDBPASS=${{ secrets.DBPASS }} appServiceAPIDBHostDBUSER=${{ secrets.DBUSER }}
        deploymentName: ${{ env.USER_ALIAS }}-prod